### ISSUE TITLE
No Link

### ISSUE THREAD

**Issue by bfillmer** [mimiflynn/supercoolneato.com#4]
No link to supercoolneato.com in the title or readme! Do you expect me to type it in the url bar?!

**Comment by mimiflynn** [comment]
You mean in this repo? or on the site?

I NEED STEPS TO REPRODUCE!!!!

🍷

**Comment by bfillmer** [comment]
You're correct, sorry.

### Steps to reproduce

1. Navigate to https://github.com/mimiflynn/supercoolneato.com
2. Muse to yourself, oh, I want to see what this looks like.
3. Look wildly around the screen for a link to supercoolneato.com
4. No link found. Realize you have to copy and paste the url, or *type it manually* into the browser.
5. Wonder if it is still 1999.
